In [1]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns

In [35]:
results = pd.read_csv('swp_results.csv')
results.head()

,input_file,SWP,delta_C,delta_L
0,/home/gbz6qn/Documents/PhD/Spring26/network_sc...,0.537112,0.408728,0.522539
1,/home/gbz6qn/Documents/PhD/Spring26/network_sc...,0.205678,0.518078,1.000000
2,/home/gbz6qn/Documents/PhD/Spring26/network_sc...,1.000000,0.000000,0.000000
3,/home/gbz6qn/Documents/PhD/Spring26/network_sc...,0.292893,0.000000,1.000000
4,/home/gbz6qn/Documents/PhD/Spring26/network_sc...,0.761424,0.000000,0.337398

In [37]:
results.describe()

              SWP     delta_C     delta_L
count  329.000000  329.000000  329.000000
mean     0.387279    0.415687    0.666192
std      0.234801    0.260863    0.431440
min      0.060565    0.000000    0.000000
25%      0.235087    0.288319    0.000000
50%      0.292893    0.433982    0.963976
75%      0.527330    0.624775    0.999964
max      1.000000    0.921357    1.000000