In [1]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
results = pd.read_csv('swp_results_mst.csv')
results.head()

,input_file,SWP,delta_C,delta_L
0,/home/gbz6qn/Documents/PhD/Spring26/network_sc...,NaN,NaN,0.082837
1,/home/gbz6qn/Documents/PhD/Spring26/network_sc...,0.938533,-0.0,0.086928
2,/home/gbz6qn/Documents/PhD/Spring26/network_sc...,0.942011,-0.0,0.082008
3,/home/gbz6qn/Documents/PhD/Spring26/network_sc...,0.945958,-0.0,0.076427
4,/home/gbz6qn/Documents/PhD/Spring26/network_sc...,NaN,NaN,0.063976

In [4]:
results.describe()

              SWP  delta_C     delta_L
count  250.000000    250.0  329.000000
mean     0.933725      0.0    0.092729
std      0.042909      0.0    0.053667
min      0.292893     -0.0    0.042866
25%      0.927992      0.0    0.076903
50%      0.937318     -0.0    0.088693
75%      0.945705     -0.0    0.101632
max      0.969689     -0.0    1.000000